Admin/Controllers/BoletoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DomainExtensions.Repositories.Interfaces;
using Domain.Entities;
using System.Data.Objects;
using DomainExtensions.Repositories;
using Domain.Service;
using MvcExtensions.Controllers;
using MvcExtensions.Security.Filters;

namespace Admin.Controllers
{
    public class BoletoController : CrudController<Boleto>
    {

        private IPersistentRepository<Boleto> boletoRepository;
        private IPersistentRepository<Faturamento> faturamentoRepository;

        public BoletoController(ObjectContext context)
            : base(context)
        {
            boletoRepository = new PersistentRepository<Boleto>(context);
            faturamentoRepository = new PersistentRepository<Faturamento>(context);
        }

        [HttpGet]
        public override ActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                var boleto = boletoRepository.Get(id.Value);
                if (boleto != null)
                {
                    return View(boleto);
                }
                else
                {
                    return RedirectToAction("List");
                }
            }
            else
            {
                return RedirectToAction("List");
            }
        }

        [ValidateInput(false)]
        public override ActionResult Edit(Boleto boleto)
        {
            boletoRepository.Save(boleto);

            return RedirectToAction("List", new { cod = "SaveSucess", boletoID = boleto.ID });
        }

        [HttpGet]
        public ActionResult Cancelar(int id)
        {
            var boleto = boletoRepository.Get(id);
            if (boleto != null)
            {
                boleto.Comando = Boleto.Comandos.Cancelar;
                if (boleto.RemessaBoletoes.Count == 0)
                {
                    boleto.StatusProcessamento = Boleto.TodosStatusProcessamento.Processado;
                    boleto.Processado = true;
                }
                else
                {
                    boleto.StatusProcessamento = Boleto.TodosStatusProcessamento.Processando;
                    boleto.Processado = false;
                }
                boleto.StatusPagamento = Boleto.TodosStatusPagamento.Cancelado;
                boletoRepository.Save(boleto);

                return RedirectToAction("List", new { cod = "SaveSucess", msg="O boleto foi cancelado com sucesso!"});
            }
            else
            {
                return RedirectToAction("List");
            }
        }

        [HttpGet]
        public ActionResult Protestar(int id)
        {
            var boleto = boletoRepository.Get(id);
            if (boleto != null)
            {
                if (boleto.RemessaBoletoes.Count > 0)
                {
                    boleto.Comando = Boleto.Comandos.Protestar;
                    boleto.Processado = false;
                    boleto.StatusProcessamento = Boleto.TodosStatusProcessamento.Processando;
                    boletoRepository.Save(boleto);

                    return RedirectToAction("List", new { cod = "SaveSucess", msg = "O boleto foi protestado com sucesso!" });
                }
                else
                {
                    return RedirectToAction("List", new { cod = "SaveFailure", msg = "Você só pode protestar um boleto que já foi enviado em alguma remessa." });
                }
            }
            else
            {
                return RedirectToAction("List");
            }
        }

        [HttpGet]
        public ActionResult Cadastro(int id)
        {
            var boleto = boletoRepository.Get(id);
            if (boleto != null)
            {
                if (boleto.RemessaBoletoes.Count > 0)
                {
                    boleto.Comando = Boleto.Comandos.ModificarDados;
                    boleto.Processado = false;
                    boleto.StatusProcessamento = Boleto.TodosStatusProcessamento.Processando;
                    boletoRepository.Save(boleto);

                    return RedirectToAction("List", new { cod = "SaveSucess", msg = "O boleto foi alterado com sucesso!" });
                }
                else
                {
                    return RedirectToAction("List", new { cod = "SaveFailure", msg = "Você só pode alterar os dados cadastrais um boleto que já foi enviado em alguma remessa." });
                }
            }
            else
            {
                return RedirectToAction("List");
            }
        }

        [HttpGet]
        public ActionResult ValorVencimento(int id)
        {
            var boleto = boletoRepository.Get(id);
            
            if (boleto != null)
            {
                if (boleto.RemessaBoletoes.Count > 0)
                {
                    boleto.Comando = Boleto.Comandos.ModificarVencimento;
                    boleto.Processado = false;
                    boleto.StatusProcessamento = Boleto.TodosStatusProcessamento.Processando;
                    boletoRepository.Save(boleto);

                   

                    return RedirectToAction("List", new { cod = "SaveSucess", msg = "O boleto foi alterado com sucesso!" });
                }
                else
                {
                    return RedirectToAction("List", new { cod = "SaveFailure", msg = "Você só pode alterar os dados cadastrais um boleto que já foi enviado em alguma remessa." });
                }
            }
            else
            {
                return RedirectToAction("List");
            }
        }

        [AreaAuthorization("Admin", "/Home/Login")]
        [AllowGroup("Socios|TI|Coordenadores|Financeiro", "/Home/AccessDenied")]
        public override ActionResult List(params object[] args)
        {
            var resultado = new List<Boleto>();
            var boletoID = 0;
            Int32.TryParse(Request.QueryString["boletoID"], out boletoID);
            if (boletoID > 0)
                resultado = boletoRepository.GetByExpression(c => c.ID == boletoID).ToList();
            else
            {
                var data = DateTime.Now.AddDays(-30);
                resultado = boletoRepository.GetByExpression
                    (c => (c.StatusPagamentoID != (int)Boleto.TodosStatusPagamento.Cancelado) 
                    || (c.StatusPagamentoID == (int)Boleto.TodosStatusPagamento.Cancelado 
                    && (!c.DataRetorno.HasValue || c.DataRetorno.Value >= data))
                    )
                    .Take(2000)
                    .OrderByDescending(c=>c.DataCriacao)
                    .ToList();
            }
            var datainicial = new DateTime();
            DateTime.TryParse(Request.QueryString["datainicial"], out datainicial);

            var datafinal = new DateTime();
            DateTime.TryParse(Request.QueryString["datafinal"], out datafinal);

            var nome = Request.QueryString["nome"];
            var numero = Request.QueryString["numero"];
            var email = Request.QueryString["email"];
            var nossonumero = Request.QueryString["nossonumero"];

            var clienteID = 0;
            Int32.TryParse(Request.QueryString["clienteID"], out clienteID);

             
            var statusprocessamento = 0;
            Int32.TryParse(Request.QueryString["statusprocessamento"], out statusprocessamento);

            var origem = 0;
            Int32.TryParse(Request.QueryString["origem"], out origem);

            var statuspagamento = 0;
            Int32.TryParse(Request.QueryString["statuspagamento"], out statuspagamento);

            var statuspagamentoped = 0;
            Int32.TryParse(Request.QueryString["statuspagamentoped"], out statuspagamentoped);

            var statusretorno = 0;
            Int32.TryParse(Request.QueryString["statusretorno"], out statusretorno);

            if (datainicial != new DateTime())
                resultado = resultado.Where(c => c.DataCriacao >= datainicial).ToList();

            if (datafinal != new DateTime())
                resultado = resultado.Where(c => c.DataCriacao <= datafinal.AddDays(1).AddMilliseconds(-1)).ToList();
            
            if (!String.IsNullOrEmpty(nome))
                resultado = boletoRepository.GetByExpression(c => (c.Pedido != null) ? c.Pedido.Cliente.Nome.ToLower().Contains(nome.ToLower()) || c.Pedido.Cliente.RazaoSocial.ToLower().Contains(nome.ToLower()) : c.Faturamento.Empresa.RazaoSocial.ToLower().Contains(nome.ToLower()) || c.SacadoNome.ToLower().Contains(nome.ToLower())).ToList();

            if (!String.IsNullOrEmpty(email))
                resultado = boletoRepository.GetByExpression(c => (c.Pedido != null) ? c.Pedido.Cliente.Email.ToLower().Contains(email.ToLower()) : c.Faturamento.Empresa.EmailContato.ToLower().Contains(email.ToLower())).ToList();

            if (!String.IsNullOrEmpty(numero))
            {
                var id = 0;
                Int32.TryParse(numero, out id);
                resultado = boletoRepository.GetByExpression(c => (c.Pedido != null) ? c.Pedido.Numero.Contains(numero) : c.Faturamento.PedidoEmpresas.Count(e => e.ID == id) > 0).ToList();
            }
            if (!String.IsNullOrEmpty(nossonumero))
            {
                resultado = boletoRepository.GetByExpression(c => c.NossoNumero == nossonumero).ToList();
            }
            if (clienteID > 0)
                resultado = resultado.Where(c => (c.Pedido != null)?c.Pedido.ClienteID == clienteID:c.Faturamento.EmpresaID == clienteID).ToList();
             
            if (statusprocessamento > 0)
                resultado = resultado.Where(c => c.StatusProcessamentoID == statusprocessamento).ToList();

            if (statuspagamento > 0)
            {
                if (statuspagamento != 3)
                    resultado = resultado.Where(c => c.StatusPagamentoID == statuspagamento).ToList();

Admin/Views/Boleto/Edit.cshtml
@model Domain.Entities.Boleto

@{
    ViewBag.Title = "Edição de boleto " + ((Model.Faturamento!=null)?Model.Faturamento.Empresa.RazaoSocial:Model.Pedido.Cliente.Nome);
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Erro != null)
{
<div class="mws-form-message mws-panel error">@ViewBag.Erro</div>
}
<div class="mws-panel grid_8">
    <div class="mws-panel-header">
        <span class="mws-i-24 i-documents-1">Edição de boleto do cliente @((Model.Faturamento!=null)?Model.Faturamento.Empresa.RazaoSocial:Model.Pedido.Cliente.Nome)</span>
    </div>
    <div class="mws-panel-body">

        <div id="erro" class="mws-form-message error" style="display:none;">ERRO! Verifique todos os campos abaixo.</div>
        @using (Html.BeginForm("Edit", "Boleto", FormMethod.Post, new { @class = "mws-form", id = "form", name = "form", enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.PedidoID)
            @Html.HiddenFor(model => model.FaturamentoID)
            @Html.HiddenFor(model => model.ComandoID)
            @Html.HiddenFor(model => model.TipoID)
            @Html.HiddenFor(model => model.StatusPagamentoID)
            @Html.HiddenFor(model => model.StatusProcessamentoID)
            @Html.HiddenFor(model => model.Carteira)
            @Html.HiddenFor(model => model.NossoNumero)
            @Html.HiddenFor(model => model.NumeroDocumento)
            @Html.HiddenFor(model => model.DataCriacao)
            @Html.HiddenFor(model => model.DataVencimento)
            @Html.HiddenFor(model => model.DataPagamento) 
            @Html.HiddenFor(model => model.CedenteCodigo)
            @Html.HiddenFor(model => model.CedenteAgencia)
            @Html.HiddenFor(model => model.CedenteRazaoSocial)
            @Html.HiddenFor(model => model.CedenteCNPJ)
            @Html.HiddenFor(model => model.CedenteContaCorrente)
            @Html.HiddenFor(model => model.RetornoID)            
            @Html.HiddenFor(model => model.RetornoErros)
            @Html.HiddenFor(model => model.RetornoCancelamento)
            @Html.HiddenFor(model => model.DataRetorno)
            @Html.HiddenFor(model => model.DataEnvioLembreteVencimento)
            @Html.HiddenFor(model => model.Observacao)
            @Html.HiddenFor(model => model.DataCEJ)
            @Html.HiddenFor(model => model.DataRecebimentoCEJ)
            @Html.HiddenFor(model => model.DataCobranca)
            @Html.HiddenFor(model => model.DataContato)
            <div class="mws-form-block">
                <div class="mws-form-row">
                    <label>Valor</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.Valor, new { @class = "mws-textinput", maxlength = "200" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Documento do sacado</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.SacadoDocumento, new { @class = "mws-textinput", maxlength = "14" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Nome do sacado</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.SacadoNome, new { @class = "mws-textinput", maxlength = "100" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Endereço do sacado</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.SacadoEndereco, new { @class = "mws-textinput", maxlength = "100" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Bairro do sacado</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.SacadoBairro, new { @class = "mws-textinput", maxlength = "50" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Cidade do sacado</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.SacadoCidade, new { @class = "mws-textinput", maxlength = "100" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>CEP do sacado</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.SacadoCEP, new { @class = "mws-textinput", maxlength = "9" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>UF do sacado</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.SacadoUF, new { @class = "mws-textinput", maxlength = "2" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Instrução</label>
                    <div class="mws-form-item small">
                        @Html.TextBoxFor(model => model.Instrucao, new { @class = "mws-textinput", maxlength = "200" })
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Processado <i>( só altere este status para <u>NÃO</u> se precisar reprocessar o boleto)</i></label>
                    <div class="mws-form-item large">
                        @Html.CheckBoxFor(model => model.Processado)  SIM
                    </div>
                </div>
                @if (Model != null)
                {
                <div class="mws-form-row">
                    <label>Status de Pagamento</label>
                    <div class="mws-form-item small">
                        @Domain.Helpers.EnumHelper.GetDescription(Model.StatusPagamento) 
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Status de Processamento</label>
                    <div class="mws-form-item small">
                        @Domain.Helpers.EnumHelper.GetDescription(Model.StatusProcessamento) 
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Data de Vencimento</label>
                    <div class="mws-form-item small">
                        @Model.DataVencimento.ToString("dd/MM/yyyy") @Html.Raw(Model.DataVencimento <= DateTime.Now && Model.StatusPagamento == Domain.Entities.Boleto.TodosStatusPagamento.AguardandoPagamento ? "<br><b>VENCIDO</b>" : "")
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Status de Pagamento</label>
                    <div class="mws-form-item small">
                        @((Model.DataPagamento.HasValue) ? Model.DataPagamento.Value.ToString("dd/MM/yyyy HH:mm") : "Pendente de pagamento")
                    </div>
                </div>  
                <div class="mws-form-row">
                    <label>Retorno</label>
                    <div class="mws-form-item small">
                       @Html.Raw(Model.RetornoID.HasValue ? "<a class=\"mws-tooltip-n\" original-title=\"" + Domain.Helpers.EnumHelper.GetDescription(Model.Retorno) + "\"><b>R: </b>" + Model.RetornoID.Value + "</a> <br /><b>E: </b>" + Model.RetornoErros + " <br /><b>C: </b>" + Model.RetornoCancelamento : "Não enviado para remessa")
                    </div>
                </div>  
                <div class="mws-form-row">
                    <input type="button" value="Imprimir Boleto" class="mws-button green small" onclick="javascript:window.open('/PedidosSite/MontaBoleto?id=@Model.ID');" />
                </div>
                }
                <div class="mws-button-row">
                    <input type="submit" class="mws-button blue" value="Salvar" id="enviar"/>
                    <input type="reset" class="mws-button gray" value="Cancelar" id="cancelar" onclick="location.href='@Url.Action("List")';"/>
                    <span id="processando" class="carregando-branco">Processando...</span>
                </div>
            </div>
        }
    </div>
</div>

@section Scripts{
<script type="text/javascript">

    $(document).ready(function () {
        $('#financeiro').addClass('active');
        $('#i_boleto').addClass('active');
        
        $("#form").validate({
            meta: "validate",
            submitHandler: function (form) {
                form.submit();
            },
            rules: {
                Valor: "required",
                SacadoDocumento: "required",
                SacadoNome: "required",
                SacadoEndereco: "required",
                SacadoBairro: "required",
                SacadoCidade: "required",
                SacadoCEP: "required",
                SacadoUF: "required",
                Instrucao: "required"
            },
            messages: {
                Valor: "O campo valor é obrigatório",
                SacadoDocumento: "O campo documento é obrigatório",
                SacadoNome: "O campo nome é obrigatório",
                SacadoEndereco: "O campo endereço é obrigatório",
                SacadoBairro: "O campo bairro é obrigatório",
                SacadoCidade: "O campo cidade é obrigatório",
                SacadoCEP: "O campo CEP é obrigatório",
                SacadoUF: "O campo UF é obrigatório",
                Instrucao: "O campo instrução é obrigatório"
            }
        });
    });
</script>
}